# Generated by Django 4.2 on 2023-05-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_contacts_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
